apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasher-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasher
  template:
    metadata:
      labels:
        app: hasher
    spec:
      containers:
        - name: hasher
          image: rvlq/hasher@sha256:dad93d2f2e64a91c5d1b0229161926c2b351df1761bf699a6b44166ba357995c