apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-share
          persistentVolumeClaim:
            claimName: share-claim
      containers:
        - name: log-output
          image: rvlq/log-output:20830
          # volumeMounts: # Mount volume
          # - name: shared-share
          #   mountPath: /code/app/shared
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
